// Package codegen generates C code from a type-checked, ownership-analysed Ore AST.
//
// The codegen strips all ownership/borrow/lifetime annotations and emits valid C:
//   - Owned String → heap-allocated char* via malloc/strdup, freed at drop points
//   - References → C pointers (no alloc/free — managed by owner)
//   - DropStmt (inserted by ownership checker) → free() for heap values
//   - println() → printf with format detection
package codegen

import (
	"fmt"
	"os"
	"os/exec"
	"strings"

	"goforust/ast"
)

// Generator walks the AST and emits C source.
type Generator struct {
	buf    strings.Builder
	indent int
}

// New creates a new Generator.
func New() *Generator { return &Generator{} }

// DumpC returns the generated C source without compiling.
func (g *Generator) DumpC(file *ast.File) string {
	g.buf.Reset()
	g.emitPreamble()
	g.emitForwards(file)
	for _, d := range file.Decls {
		g.genDecl(d)
		g.nl()
	}
	return g.buf.String()
}

// Generate emits C source for the file, writes it to a temp file, and
// invokes gcc to produce a native binary at outputPath.
func (g *Generator) Generate(file *ast.File, outputPath string) error {
	g.buf.Reset()
	g.emitPreamble()
	g.emitForwards(file)
	for _, d := range file.Decls {
		g.genDecl(d)
		g.nl()
	}

	tmp, err := os.CreateTemp("", "goforust_*.c")
	if err != nil {
		return fmt.Errorf("create temp: %w", err)
	}
	tmpPath := tmp.Name()
	defer os.Remove(tmpPath)

	if _, err := tmp.WriteString(g.buf.String()); err != nil {
		tmp.Close()
		return err
	}
	tmp.Close()

	cmd := exec.Command("gcc", "-o", outputPath, tmpPath, "-lm")
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	if err := cmd.Run(); err != nil {
		fmt.Fprintf(os.Stderr, "\n--- generated C ---\n%s\n---\n", g.buf.String())
		return fmt.Errorf("gcc: %w", err)
	}
	return nil
}

// ─────────────────────────────────────────────────────────────────────────────
// Preamble & forward declarations
// ─────────────────────────────────────────────────────────────────────────────

func (g *Generator) emitPreamble() {
	g.emit("/* Generated by go-for-rust (Ore compiler) */\n")
	g.emit("#include <stdio.h>\n")
	g.emit("#include <stdlib.h>\n")
	g.emit("#include <string.h>\n\n")
	g.emit("typedef long        _OreInt;\n")
	g.emit("typedef char*       _OreString;\n")
	g.emit("typedef int         _OreBool;\n")
	g.emit("#define true   1\n")
	g.emit("#define false  0\n\n")
	// Helper: make an owned heap string from a literal.
	g.emit("static _OreString _ore_string_new(const char* s) { return strdup(s); }\n")
	g.emit("static void _ore_drop_string(_OreString* s) { if(*s){free(*s);*s=NULL;} }\n\n")
}

func (g *Generator) emitForwards(file *ast.File) {
	for _, d := range file.Decls {
		if fn, ok := d.(*ast.FnDecl); ok {
			g.emitFnSig(fn)
			g.emit(";\n")
		}
	}
	g.nl()
}

// ─────────────────────────────────────────────────────────────────────────────
// Declarations
// ─────────────────────────────────────────────────────────────────────────────

func (g *Generator) genDecl(d ast.Decl) {
	switch decl := d.(type) {
	case *ast.FnDecl:
		g.genFn(decl)
	case *ast.StructDecl:
		g.genStruct(decl)
	case *ast.ImplBlock:
		for _, m := range decl.Methods {
			g.genFn(m)
		}
	}
}

func (g *Generator) emitFnSig(fn *ast.FnDecl) {
	retC := "void"
	if fn.Name == "main" {
		retC = "int"
	} else if fn.ReturnType != nil {
		retC = oreToCType(fn.ReturnType)
	}

	var params []string
	for _, p := range fn.Params {
		params = append(params, fmt.Sprintf("%s %s", oreToCType(p.Type), p.Name))
	}
	paramStr := strings.Join(params, ", ")
	if paramStr == "" {
		paramStr = "void"
	}
	g.emit(fmt.Sprintf("%s %s(%s)", retC, fn.Name, paramStr))
}

func (g *Generator) genFn(fn *ast.FnDecl) {
	g.emitFnSig(fn)
	g.emit(" {\n")
	g.indent++
	g.genBlock(fn.Body)
	if fn.Name == "main" {
		g.line("return 0;")
	}
	g.indent--
	g.emit("}\n")
}

func (g *Generator) genStruct(s *ast.StructDecl) {
	g.emit(fmt.Sprintf("typedef struct _%s {\n", s.Name))
	for _, f := range s.Fields {
		g.emit(fmt.Sprintf("    %s %s;\n", oreToCType(f.Type), f.Name))
	}
	g.emit(fmt.Sprintf("} %s;\n", s.Name))
}

// ─────────────────────────────────────────────────────────────────────────────
// Statements
// ─────────────────────────────────────────────────────────────────────────────

func (g *Generator) genBlock(block *ast.BlockStmt) {
	if block == nil {
		return
	}
	for _, s := range block.Stmts {
		g.genStmt(s)
	}
}

func (g *Generator) genStmt(s ast.Stmt) {
	switch stmt := s.(type) {
	case *ast.LetDecl:
		cType := "_OreInt" // default
		if stmt.Type != nil {
			cType = oreToCType(stmt.Type)
		} else if stmt.Value != nil {
			cType = inferCType(stmt.Value)
		}
		if stmt.Value != nil {
			val := g.genExpr(stmt.Value)
			// Wrap string literals in _ore_string_new for owned strings.
			if cType == "_OreString" {
				if _, isLit := stmt.Value.(*ast.StringLit); isLit {
					val = fmt.Sprintf("_ore_string_new(%s)", val)
				}
			}
			g.line(fmt.Sprintf("%s %s = %s;", cType, stmt.Name, val))
		} else {
			g.line(fmt.Sprintf("%s %s;", cType, stmt.Name))
		}

	case *ast.AssignStmt:
		g.line(fmt.Sprintf("%s %s %s;", g.genExpr(stmt.Target), stmt.Op, g.genExpr(stmt.Value)))

	case *ast.IncDecStmt:
		g.line(fmt.Sprintf("%s%s;", g.genExpr(stmt.Target), stmt.Op))

	case *ast.ExprStmt:
		g.line(fmt.Sprintf("%s;", g.genExpr(stmt.Expr)))

	case *ast.ReturnStmt:
		if stmt.Value != nil {
			g.line(fmt.Sprintf("return %s;", g.genExpr(stmt.Value)))
		} else {
			g.line("return;")
		}

	case *ast.IfStmt:
		g.iline(fmt.Sprintf("if (%s) {", g.genExpr(stmt.Cond)))
		g.indent++
		g.genBlock(stmt.Then)
		g.indent--
		if stmt.Else != nil {
			switch e := stmt.Else.(type) {
			case *ast.BlockStmt:
				g.line("} else {")
				g.indent++
				g.genBlock(e)
				g.indent--
				g.line("}")
			case *ast.IfStmt:
				g.iline("} else ")
				g.genElseIf(e)
			}
		} else {
			g.line("}")
		}

	case *ast.WhileStmt:
		g.iline(fmt.Sprintf("while (%s) {", g.genExpr(stmt.Cond)))
		g.indent++
		g.genBlock(stmt.Body)
		g.indent--
		g.line("}")

	case *ast.ForStmt:
		initStr := g.genSimpleStmt(stmt.Init)
		condStr := ""
		if stmt.Cond != nil {
			condStr = g.genExpr(stmt.Cond)
		}
		postStr := g.genSimpleStmt(stmt.Post)
		g.iline(fmt.Sprintf("for (%s; %s; %s) {", initStr, condStr, postStr))
		g.indent++
		g.genBlock(stmt.Body)
		g.indent--
		g.line("}")

	case *ast.DropStmt:
		// Insert free() for owned heap strings; other types need no runtime drop.
		g.line(fmt.Sprintf("_ore_drop_string(&%s); /* drop %s */", stmt.VarName, stmt.VarName))

	case *ast.BlockStmt:
		g.line("{")
		g.indent++
		g.genBlock(stmt)
		g.indent--
		g.line("}")
	}
}

func (g *Generator) genSimpleStmt(s ast.Stmt) string {
	if s == nil {
		return ""
	}
	switch stmt := s.(type) {
	case *ast.LetDecl:
		cType := "_OreInt"
		if stmt.Type != nil {
			cType = oreToCType(stmt.Type)
		}
		if stmt.Value != nil {
			return fmt.Sprintf("%s %s = %s", cType, stmt.Name, g.genExpr(stmt.Value))
		}
		return fmt.Sprintf("%s %s", cType, stmt.Name)
	case *ast.AssignStmt:
		return fmt.Sprintf("%s %s %s", g.genExpr(stmt.Target), stmt.Op, g.genExpr(stmt.Value))
	case *ast.IncDecStmt:
		return fmt.Sprintf("%s%s", g.genExpr(stmt.Target), stmt.Op)
	case *ast.ExprStmt:
		return g.genExpr(stmt.Expr)
	}
	return ""
}

func (g *Generator) genElseIf(stmt *ast.IfStmt) {
	g.emit(fmt.Sprintf("if (%s) {\n", g.genExpr(stmt.Cond)))
	g.indent++
	g.genBlock(stmt.Then)
	g.indent--
	if stmt.Else != nil {
		switch e := stmt.Else.(type) {
		case *ast.BlockStmt:
			g.line("} else {")
			g.indent++
			g.genBlock(e)
			g.indent--
			g.line("}")
		case *ast.IfStmt:
			g.iline("} else ")
			g.genElseIf(e)
		}
	} else {
		g.line("}")
	}
}

// ─────────────────────────────────────────────────────────────────────────────
// Expressions
// ─────────────────────────────────────────────────────────────────────────────

func (g *Generator) genExpr(e ast.Expr) string {
	if e == nil {
		return ""
	}
	switch expr := e.(type) {
	case *ast.IntLit:
		return fmt.Sprintf("%dL", expr.Value)
	case *ast.StringLit:
		return fmt.Sprintf("%q", expr.Value)
	case *ast.BoolLit:
		if expr.Value {
			return "1"
		}
		return "0"
	case *ast.Ident:
		return expr.Name
	case *ast.BinaryExpr:
		return fmt.Sprintf("(%s %s %s)", g.genExpr(expr.Left), expr.Op, g.genExpr(expr.Right))
	case *ast.UnaryExpr:
		return fmt.Sprintf("(%s%s)", expr.Op, g.genExpr(expr.Operand))
	case *ast.BorrowExpr:
		// &x  → &x  (pointer in C)
		inner := g.genExpr(expr.Operand)
		return fmt.Sprintf("(&%s)", inner)
	case *ast.MoveExpr:
		return g.genExpr(expr.Operand)
	case *ast.SelectorExpr:
		return fmt.Sprintf("%s%s%s", g.genExpr(expr.X), expr.Sep, expr.Sel)
	case *ast.CallExpr:
		return g.genCall(expr)
	case *ast.StructLit:
		return g.genStructLit(expr)
	}
	return "/* ? */"
}

func (g *Generator) genCall(c *ast.CallExpr) string {
	// Built-in println
	if ident, ok := c.Func.(*ast.Ident); ok && ident.Name == "println" {
		return g.genPrintln(c.Args)
	}
	// Selector call: obj.method(...)
	fnStr := g.genExpr(c.Func)
	var args []string
	for _, a := range c.Args {
		args = append(args, g.genExpr(a))
	}
	return fmt.Sprintf("%s(%s)", fnStr, strings.Join(args, ", "))
}

func (g *Generator) genPrintln(args []ast.Expr) string {
	if len(args) == 0 {
		return `printf("\n")`
	}
	var fmtParts []string
	var cArgs []string
	for _, a := range args {
		switch arg := a.(type) {
		case *ast.StringLit:
			fmtParts = append(fmtParts, "%s")
			cArgs = append(cArgs, fmt.Sprintf("%q", arg.Value))
		case *ast.IntLit:
			fmtParts = append(fmtParts, "%ld")
			cArgs = append(cArgs, fmt.Sprintf("%dL", arg.Value))
		case *ast.BoolLit:
			fmtParts = append(fmtParts, "%d")
			if arg.Value {
				cArgs = append(cArgs, "1")
			} else {
				cArgs = append(cArgs, "0")
			}
		default:
			fmtParts = append(fmtParts, "%ld")
			cArgs = append(cArgs, g.genExpr(a))
		}
	}
	fmtStr := strings.Join(fmtParts, " ") + "\\n"
	allArgs := append([]string{fmt.Sprintf("%q", fmtStr)}, cArgs...)
	return fmt.Sprintf("printf(%s)", strings.Join(allArgs, ", "))
}

func (g *Generator) genStructLit(s *ast.StructLit) string {
	var fields []string
	for _, f := range s.Fields {
		fields = append(fields, fmt.Sprintf(".%s = %s", f.Name, g.genExpr(f.Value)))
	}
	return fmt.Sprintf("(%s){%s}", s.TypeName, strings.Join(fields, ", "))
}

// ─────────────────────────────────────────────────────────────────────────────
// Type mapping
// ─────────────────────────────────────────────────────────────────────────────

func oreToCType(t *ast.TypeExpr) string {
	if t == nil {
		return "void"
	}
	base := ""
	switch t.Name {
	case "Int":
		base = "_OreInt"
	case "String":
		base = "_OreString"
	case "Bool":
		base = "_OreBool"
	case "Self", "":
		base = "void*"
	default:
		base = t.Name // user struct
	}
	// References become pointers in C.
	if t.Mode == ast.Shared || t.Mode == ast.MutBorrow {
		return base + "*"
	}
	return base
}

func inferCType(e ast.Expr) string {
	switch e.(type) {
	case *ast.StringLit:
		return "_OreString"
	case *ast.IntLit:
		return "_OreInt"
	case *ast.BoolLit:
		return "_OreBool"
	}
	return "_OreInt"
}

// ─────────────────────────────────────────────────────────────────────────────
// Emit helpers
// ─────────────────────────────────────────────────────────────────────────────

func (g *Generator) emit(s string)  { g.buf.WriteString(s) }
func (g *Generator) nl()            { g.buf.WriteByte('\n') }
func (g *Generator) ind() string    { return strings.Repeat("    ", g.indent) }
func (g *Generator) line(s string)  { g.buf.WriteString(g.ind() + s + "\n") }
func (g *Generator) iline(s string) { g.buf.WriteString(g.ind() + s + "\n") }
